CREATE TABLE [dbo].[DataTypeGhostValues] (
    [TYPE_NAME]      NVARCHAR (50) NOT NULL,
    [LITERAL_PREFIX] NVARCHAR (50) NULL,
    [LITERAL_SUFFIX] NVARCHAR (50) NULL,
    CONSTRAINT [PK_DataTypeGhostValues] PRIMARY KEY CLUSTERED ([TYPE_NAME] ASC)
);


GO

