DROP TABLE dbo.TableColumnMap
DROP TABLE dbo.Columns
DROP TABLE dbo.TableVersion
DROP TABLE dbo.Tables
DROP TABLE dbo.Abbreviation
DROP TABLE dbo.AbbreviationStyle
DROP TABLE dbo.RecordSource
DROP TABLE dbo.Organization
DROP TABLE dbo.GeoLocation
DROP TABLE dbo.DataTypeMap
DROP TABLE dbo.SourceType